version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    working_directory: ~/floodiq-javascript
    docker:
      - image: cimg/node:14.16.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # restore dependency cache
          key: dependency-cache-v2-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # save dependency cache
          key: dependency-cache-v2-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run code coverage
          name: code-coverage
          command: npm run test:coverage
      - codecov/upload:
          file: coverage/lcov.info


