version: 2.1
# orbs:
#   # codecov: codecov/codecov@1.0.4
jobs:
  build:
    working_directory: ~/floodiq-javascript
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # restrore dependency cache
          key: dependency-cache-{{ checksum "package.json" ***REMOVED******REMOVED***
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # save dependency cache
          key: dependency-cache-{{ checksum "package.json" ***REMOVED******REMOVED***
          paths:
            - ./node_modules
      - run: # run code coverage
          name: code-coverage
          command: npm run test:coverage
      - codecov/upload:
          token: aab11a0b-e97e-47a2-8d21-310175cdd607
          file: coverage/lcov.info
      - store_artifacts: # save test results
          path: test-results.xml
      - store_artifacts: # save coverage results
          path: coverage
      - store_test_results:
          path: test-results.xml


