version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
  kubernetes: circleci/kubernetes@0.1.0
jobs:
  build:
    working_directory: ~/floodiq-javascript
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # restrore dependency cache
          key: dependency-cache-{{ checksum "package.json" ***REMOVED******REMOVED***
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # save dependency cache
          key: dependency-cache-{{ checksum "package.json" ***REMOVED******REMOVED***
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test
      - run: # run code coverage
          name: code-coverage
          command: npm test --coverage
      - store_artifacts: # save test results
          path: test-results.xml
          prefix: tests
      - store_artifacts: # save coverage results
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml


